.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. picscoin_qt test_picscoin_qt
clean: FORCE
	$(MAKE) -C .. picscoin_qt_clean test_picscoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_picscoin_qt_check
picscoin-qt picscoin-qt.exe: FORCE
	 $(MAKE) -C .. picscoin_qt
